CREATE OR REPLACE TYPE PRODUCTOS_OBJTYP AS OBJECT
( NP NUMBER(6),
DESCRIP VARCHAR2(20),
PRECIO NUMBER(6,2),
IVA NUMBER(2)
);
CREATE TYPE LFACTURAS_OBJTYP AS OBJECT
( NL NUMBER(3),
CTD NUMBER(3),
PRECIO NUMBER(6,2),
IVA NUMBER(2),
PRODUCTO REF PRODUCTOS_OBJTYP
);

CREATE TYPE LFACTURAS_NTYP AS TABLE OF LFACTURAS_OBJTYP;
DROP TYPE FACTURAS_OBJTYP;
CREATE TYPE FACTURAS_OBJTYP AS OBJECT(
NF NUMBER(4),
FECHA DATE,
PRECIO_TOTAL NUMBER(8,2),
LINEAS LFACTURAS_NTYP
);

CREATE TABLE PRODUCTOS_TAB OF PRODUCTOS_OBJTYP(
NP PRIMARY KEY,
DESCRIP NOT NULL,
CHECK(PRECIO >= 0),
CHECK(IVA >0)
);

CREATE TABLE FACTURAS_TAB OF FACTURAS_OBJTYP(
NF PRIMARY KEY,
FECHA NOT NULL,
CHECK(PRECIO_TOTAL >0))
NESTED TABLE LINEAS STORE AS LFACTURAS_NTAB
((PRIMARY KEY(NESTED_TABLE_ID,NL),
CHECK(CTD>=0),
CHECK(PRECIO>=0),
CHECK(IVA> 0)));

ALTER TABLE LFACTURAS_NTAB ADD( SCOPE FOR(PRODUCTO) IS PRODUCTOS_TAB);

INSERT INTO PRODUCTOS_TAB VALUES(
PRODUCTOS_OBJTYP(1,'Pipas Facundo',1.5,21)
);

INSERT INTO FACTURAS_TAB VALUES(
1,SYSDATE,NULL,LFACTURAS_NTYP(
    LFACTURAS_OBJTYP(1,25,1.5,21,
                (SELECT REF(P) FROM PRODUCTOS_TAB P WHERE NP=1)))
);

INSERT INTO TABLE (SELECT LINEAS FROM FACTURAS_TAB WHERE NF=1) VALUES(
LFACTURAS_OBJTYP(2,25,1.5,21,(SELECT REF(P) FROM PRODUCTOS_TAB P WHERE NP=1))
);

SELECT * FROM TABLE(SELECT LINEAS FROM FACTURAS_TAB WHERE NF=1) LF, PRODUCTOS_TAB P WHERE LF.PRODUCTO=REF(P);CREATE OR REPLACE TYPE PRODUCTOS_OBJTYP AS OBJECT
( NP NUMBER(6),
DESCRIP VARCHAR2(20),
PRECIO NUMBER(6,2),
IVA NUMBER(2)
);
CREATE TYPE LFACTURAS_OBJTYP AS OBJECT
( NL NUMBER(3),
CTD NUMBER(3),
PRECIO NUMBER(6,2),
IVA NUMBER(2),
PRODUCTO REF PRODUCTOS_OBJTYP
);

CREATE TYPE LFACTURAS_NTYP AS TABLE OF LFACTURAS_OBJTYP;
DROP TYPE FACTURAS_OBJTYP;
CREATE TYPE FACTURAS_OBJTYP AS OBJECT(
NF NUMBER(4),
FECHA DATE,
PRECIO_TOTAL NUMBER(8,2),
LINEAS LFACTURAS_NTYP
);

CREATE TABLE PRODUCTOS_TAB OF PRODUCTOS_OBJTYP(
NP PRIMARY KEY,
DESCRIP NOT NULL,
CHECK(PRECIO >= 0),
CHECK(IVA >0)
);

CREATE TABLE FACTURAS_TAB OF FACTURAS_OBJTYP(
NF PRIMARY KEY,
FECHA NOT NULL,
CHECK(PRECIO_TOTAL >0))
NESTED TABLE LINEAS STORE AS LFACTURAS_NTAB
((PRIMARY KEY(NESTED_TABLE_ID,NL),
CHECK(CTD>=0),
CHECK(PRECIO>=0),
CHECK(IVA> 0)));

ALTER TABLE LFACTURAS_NTAB ADD( SCOPE FOR(PRODUCTO) IS PRODUCTOS_TAB);

INSERT INTO PRODUCTOS_TAB VALUES(
PRODUCTOS_OBJTYP(1,'Pipas Facundo',1.5,21)
);

INSERT INTO FACTURAS_TAB VALUES(
1,SYSDATE,NULL,LFACTURAS_NTYP(
    LFACTURAS_OBJTYP(1,25,1.5,21,
                (SELECT REF(P) FROM PRODUCTOS_TAB P WHERE NP=1)))
);

INSERT INTO TABLE (SELECT LINEAS FROM FACTURAS_TAB WHERE NF=1) VALUES(
LFACTURAS_OBJTYP(2,25,1.5,21,(SELECT REF(P) FROM PRODUCTOS_TAB P WHERE NP=1))
);

SELECT * FROM TABLE(SELECT LINEAS FROM FACTURAS_TAB WHERE NF=1) LF, PRODUCTOS_TAB P WHERE LF.PRODUCTO=REF(P);